-- Nachbau der betroffenen Tabellen fuer scripts/test-protokoll.mjs (lokales Postgres per PGlite).
-- Spalten wie in der Live-Datenbank am 09.10.2026; ohne RLS/Policies der Originale, ohne Volltext-Default.
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth;
create function auth.jwt() returns jsonb language sql stable as $$
  select coalesce(nullif(current_setting('request.jwt.claim', true), ''), nullif(current_setting('request.jwt.claims', true), ''))::jsonb
$$;
create function public.is_app_admin() returns boolean language sql stable as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'app_role') = 'admin', false) $$;
create function public.is_app_user() returns boolean language sql stable as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'app_role') in ('admin','user'), false) $$;

create table public.abrechnung_freigaben (woche text not null, freigegeben_am timestamptz default now(), freigegeben_von text not null, anzahl integer not null, summe numeric not null, primary key (woche));
create table public.abrechnung_posten (id bigint generated by default as identity, woche text not null, fahrer_name text not null, betrag numeric(10,2) not null, text text not null, angelegt_von text not null, angelegt_am timestamptz default now(), primary key (id));
create table public.app_users (id integer generated by default as identity, name text not null, role text default 'user', created_at timestamptz default now(), auth_id uuid, primary key (id));
create table public.companies (id uuid default gen_random_uuid(), slug text not null, name text not null, short_name text default '', address text default '', uid text default '', fn text default '', iban text default '', bic text default 'GIBAATWWXXX', gf text default '', email text default '', tel text default '', color_scheme text default 'blau', logo_url text default '', is_default boolean default false, sort_order integer default 99, created_at timestamptz default now(), primary key (id));
create table public.customers (id uuid default gen_random_uuid(), slug text not null, name text not null, short_name text default '', address text default '', uid text default '', color_scheme text default 'grau', is_default boolean default false, sort_order integer default 99, created_at timestamptz default now(), primary key (id));
create table public.fahrer_app_zugang (notion_fahrer_id integer not null, auth_user_id uuid not null, angelegt_am timestamptz default now(), angelegt_von text not null, pin_geaendert_am timestamptz, gesperrt boolean default false, gesperrt_am timestamptz, primary key (notion_fahrer_id));
create table public.kassabuch (id bigint generated by default as identity, datum date not null, art text not null, betrag numeric(10,2) not null, name text not null, text text, storno_von bigint, angelegt_von text not null, angelegt_am timestamptz default now(), nr integer, pruefsumme text, quelle text default 'hand', woche_abr text, posten_id bigint, primary key (id));
create table public.kassier_zahlungen (id uuid default gen_random_uuid(), fahrer_name text not null, woche text not null, betrag numeric(10,2) not null, typ text not null, verrechnet_mit_woche text, kassiert_von text not null, kassiert_at timestamptz default now(), note text, primary key (id));
create table public.lohn_personen (firma_nr text not null, ma_nr integer not null, notion_fahrer_id integer not null, gesetzt_von text not null, gesetzt_am timestamptz default now(), primary key (firma_nr, ma_nr));
create table public.mietverhaeltnisse (id integer generated by default as identity, kurz text not null, name text not null, adresse text not null, uid text, fn text, gueltig_von date, gueltig_bis date, primary key (id));
create table public.name_aliases (csv_name text not null, fahrer_name text not null, created_at timestamptz default now(), primary key (csv_name));
create table public.notion_fahrer (notion_page_id text not null, notion_fahrer_id integer, name text, telefon text, email text, status text, firma text, roh jsonb not null, sync_run_id uuid, aktualisiert_am timestamptz default now(), primary key (notion_page_id));
create table public.post_ausgang (id uuid default gen_random_uuid(), eingang_id uuid, gz text not null, an text not null, betreff text not null, text text not null, mietverhaeltnis_id integer, gmail_message_id text, gmail_thread_id text, gesendet_am timestamptz, gesendet_von uuid, test_an text, fehler text, quelle text not null, erstellt_am timestamptz default now(), primary key (id));
create table public.post_eingang (id uuid default gen_random_uuid(), quelle text not null, delivery_id text, sha256 text not null, datei_pfad text not null, dateiname text, usp_absender text, usp_betreff text, zugestellt_am timestamptz, eingelesen_am timestamptz default now(), art text, gz text, behoerde text, kennzeichen text, kennzeichen_key text, tatzeit timestamptz, tatort text, delikt text, betrag numeric(10,2), frist date, antwort_email text, volltext text, auslese_roh jsonb, pruef_grund text, fahrer_vorschlag_id integer, fahrer_id integer, status text default 'neu', freigegeben_am timestamptz, freigegeben_von uuid, erledigt_am timestamptz, erledigt_von uuid, notiz text, suche tsvector, primary key (id));
create table public.settlements (id integer generated by default as identity, woche text not null, fahrer_name text not null, telefon text, mietmodell text, miete numeric(10,2), bolt_brutto numeric(10,2) default 0, bolt_auszahlung numeric(10,2) default 0, uber_fahrpreis numeric(10,2) default 0, uber_auszahlung numeric(10,2) default 0, mypos_summe numeric(10,2) default 0, bruttoumsatz_gesamt numeric(10,2) default 0, wir_bekommen numeric(10,2) default 0, prozent_abzug numeric(10,2) default 0, abzug_gesamt numeric(10,2) default 0, auszahlung numeric(10,2) default 0, status text default 'berechnet', telegram_gesendet boolean default false, created_at timestamptz default now(), korrektur numeric(10,2) default 0, korrektur_note text, lohn numeric default 0, primary key (id));
create table public.sync_runs (id uuid default gen_random_uuid(), verbindung_id uuid not null, start timestamptz default now(), ende timestamptz, zeitraum_von date, zeitraum_bis date, anzahl integer default 0, status text default 'laeuft', fehler text, primary key (id));
create table public.verbindungen (id uuid default gen_random_uuid(), anbieter text not null, firma text, vault_secret_id uuid not null, status text default 'aktiv', letzter_abruf timestamptz, letzter_fehler text, erstellt_am timestamptz default now(), externe_id text, gueltig_bis timestamptz, primary key (id));
create table public.zuordnung_manuell (anbieter text not null, driver_uuid text not null, notion_fahrer_id integer not null, gesetzt_von text not null, gesetzt_am timestamptz default now(), primary key (anbieter, driver_uuid));

grant usage on schema public, auth to anon, authenticated, service_role;
grant all on all tables in schema public to authenticated, service_role;

-- Bestand VOR der Migration (wird Altbestand bzw. Quelle fuer den Verlauf)
insert into public.notion_fahrer (notion_page_id, notion_fahrer_id, name, roh) values ('p14', 14, 'Ivan Beispiel', '{}');
insert into public.settlements (woche, fahrer_name, miete, auszahlung) values
  ('2026-W39', 'Ivan Beispiel', 300, 120), ('2026-W40', 'Ivan Beispiel', 300, 90), ('2026-W40', 'Anna Muster', 300, 50),
  ('2026-W40', 'Karl Probe', 300, -20), ('2026-W40', 'Zoe Letzte', 300, 10);
insert into public.abrechnung_freigaben values ('2026-W39', '2026-09-28 10:00+02', 'Boyko', 4, 500);
insert into public.abrechnung_posten (woche, fahrer_name, betrag, text, angelegt_von, angelegt_am) values ('2026-W39', 'Ivan Beispiel', 70, 'Pickerl', 'Stefan', '2026-10-03 09:00+02');
insert into public.kassier_zahlungen (fahrer_name, woche, betrag, typ, kassiert_von, kassiert_at) values ('Karl Probe', '2026-W39', 150, 'bar', 'Bislan', '2026-10-01 12:00+02');
insert into public.zuordnung_manuell values ('uber', 'u-1', 14, 'Boyko', '2026-09-24 08:00+02'), ('bolt', 'b-9', 99, 'Boyko', '2026-09-24 08:05+02');
insert into public.lohn_personen values ('200218', 5, 14, 'Boyko', '2026-09-25 08:00+02');
insert into public.fahrer_app_zugang (notion_fahrer_id, auth_user_id, angelegt_von, angelegt_am) values (14, gen_random_uuid(), 'Boyko', '2026-09-23 18:00+02');
insert into public.post_eingang (quelle, sha256, datei_pfad, art, gz, volltext) values ('usp', 'abc', 'post/a.pdf', 'strafverfuegung', 'MA67/1', 'Text');
insert into public.app_users (name, role, auth_id) values ('Boyko', 'admin', '00000000-0000-0000-0000-0000000000b0'), ('Stefan', 'user', '00000000-0000-0000-0000-0000000000a1');
insert into public.post_ausgang (gz, an, betreff, text, quelle, gesendet_am, gesendet_von) values
  ('MA67/1', 'le@ma67.wien.gv.at', 'Lenkerauskunft', 'vermietet an', 'dashboard', '2026-09-30 11:00+02', '00000000-0000-0000-0000-0000000000a1'),
  ('MA67/2', 'le@ma67.wien.gv.at', 'Lenkerauskunft', 'vermietet an', 'gmail', '2026-09-29 11:00+02', null),
  ('MA67/3', 'le@ma67.wien.gv.at', 'Lenkerauskunft', 'Entwurf', 'dashboard', null, null);
insert into public.verbindungen (id, anbieter, firma, vault_secret_id) values
  ('00000000-0000-0000-0000-00000000000e', 'uber', 'ee_taxi_kg', gen_random_uuid()), ('00000000-0000-0000-0000-00000000000b', 'bolt', 'serdo', gen_random_uuid());
insert into public.sync_runs (verbindung_id, start, ende, anzahl, status, fehler) values
  ('00000000-0000-0000-0000-00000000000e', '2026-10-05 06:00+02', '2026-10-05 06:01+02', 100, 'ok', null),
  ('00000000-0000-0000-0000-00000000000e', '2026-10-05 12:00+02', '2026-10-05 12:01+02', 210, 'ok', null),
  ('00000000-0000-0000-0000-00000000000e', '2026-10-05 18:00+02', '2026-10-05 18:01+02', 0, 'fehler', 'HTTP 401'),
  ('00000000-0000-0000-0000-00000000000b', '2026-10-05 07:00+02', '2026-10-05 07:01+02', 40, 'ok', null),
  ('00000000-0000-0000-0000-00000000000b', '2026-10-06 07:00+02', null, 0, 'laeuft', null);
insert into public.kassabuch (datum, art, betrag, name, text, angelegt_von, angelegt_am, nr, storno_von) values
  ('2026-10-05', 'aus', 40, 'Stefan', 'Tanken', 'Stefan', '2026-10-05 15:00+02', 1, null),
  ('2026-10-05', 'ein', 40, 'Stefan', 'Storno Nr. 1', 'Stefan', '2026-10-05 15:10+02', 2, 1);
